services:
  btn-game:
    build: .
    volumes: 
      - /home/lauri/log/vinskis-great-button-game.fi/gunicorn:/usr/src/app/log/gunicorn
      - /home/lauri/sqlite/button-game.db:/usr/src/app/button-game.db
    ports:
      - "${GUNICORN_PORT}:${GUNICORN_PORT}"
    environment:
      - GUNICORN_PORT=${GUNICORN_PORT}
